### PR TITLE
New tag

### PR DESCRIPTION
**Pull request by ImErick**
Implement a new tag to show all (actives) testimonial quotes, this is an option to show all quotes without number parameter
Add the tag to documentation and provide an example 'how to show your quotes'

### CODE REVIEW

**Comment by paltman** [comment]
I would prefer if we just made the argument to `{% testimonials %}` optional.

You can do this by changing the `def testimonials(number):` function declaration to: `def testimonials(number=None):` and then checking if `number is None` in the function to decide whether or not to slice the queryset.

Thanks!

**Comment by ImErick** [comment]
Thanks for the feedback @paltman I update testimonial tag and update the documentation about them

**Comment by jtauber** [comment]
@paltman do we just need to update the test matrix and retry this? seems like something worth doing for 16.07

**Comment by paltman** [comment]
@jtauber yeah, the matrix on master should make this work.

**Pull request merged**
